# Generated by Django 4.2.16 on 2024-10-23 04:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
